### PR TITLE
Manage xcdatamodeld

### LINKED ISSUE #26: Improve error message when passing an xcdatamodeld
When you use gyro with this command line : `gyro -m .../Models/DataModel.xcdatamodeld`, it fails with error : 
```
! Unable to find contents of xcdatamodel
/Users/steven_watremez/workspace/tools/gyro/lib/gyro/log.rb:42:in `fail!': Unable to find contents of xcdatamodel (RuntimeError)
	from /Users/steven_watremez/workspace/tools/gyro/lib/gyro/parser/xcdatamodel/xcdatamodel.rb:38:in `initialize'
	from bin/gyro:123:in `new'
	from bin/gyro:123:in `<main>'
```

This is because `gyro` expects an `.xcdatamodel` (to look at the `contents` XML file inside it) and not an `.xcdatamodeld`. But the error is not very friendly.

A solution to avoid this error would be to raise a specific error like : `please target an xcdatamodel inside your xcdatamodeld`

💡  In addition for user that use an `xcdatamodel` which happens to be inside an `xcdatamodeld` bundle, gyro could raise a warning like: `you use an xcdatamodeld, please be sure you target the correct version of your xcdatamodel. Actual version using by gyro is : MyDataModel-V2.xcdatamodel` so that people don't forget about updating the command line when they create a new datamodel version

### PR DESCRIPTION
**Pull request by StevenWatremez**
This PR fixes #26.

### CODE REVIEW

File: lib/gyro/parser/xcdatamodel/xcdatamodel.rb [hunk 1]
```diff
@@ -36,13 +36,19 @@ class XCDataModel
         attr_accessor :entities
 
         def initialize(xcdatamodel_dir)
-          contents_file = File.join(xcdatamodel_dir, 'contents')
-          Gyro::Log.fail!('Unable to find contents of xcdatamodel', stacktrace: true) unless File.exist?(contents_file)
+          is_xcdatamodeld = xcdatamodel_dir.extname != '.xcdatamodeld'
+          Gyro::Log.fail!('Please target an xcdatamodel inside your xcdatamodeld') unless is_xcdatamodeld
+          if xcdatamodel_dir.to_path.include?('.xcdatamodeld')
```
Comment (StevenWatremez) [inline lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: Change this : `xcdatamodel_dir.parent.extname  == '.xcdatamodeld`

File: spec/gyro/xcdatamodel_spec.rb [hunk 2]
```diff
@@ -24,10 +24,10 @@ module Gyro
         .to raise_error 'Unable to find contents of xcdatamodel'
     end
 
-    it 'check raising relationship error' do
-      xcdatamodel_dir = fixture('xcdatamodel', 'error_relationship.xcdatamodel')
+    it 'check raise an error for xcdatamodeld' do
+      xcdatamodel_dir = fixture('xcdatamodel', 'Model.xcdatamodeld')
       expect { Parser::XCDataModel::XCDataModel.new(xcdatamodel_dir) }
-        .to raise_error 'The relationship "user" from "FidelityCard" is wrong - please fix it'
```
Comment (AliSoftware) [inline spec/gyro/xcdatamodel_spec.rb]: The new spec is good, but why did the old `"check raising relationship error"` spec disappear?

Comment (StevenWatremez) [reply spec/gyro/xcdatamodel_spec.rb]: My bad I will fix this

File: lib/gyro/parser/xcdatamodel/xcdatamodel.rb [hunk 3]
```diff
@@ -36,13 +36,19 @@ class XCDataModel
         attr_accessor :entities
 
         def initialize(xcdatamodel_dir)
-          contents_file = File.join(xcdatamodel_dir, 'contents')
-          Gyro::Log.fail!('Unable to find contents of xcdatamodel', stacktrace: true) unless File.exist?(contents_file)
+          is_xcdatamodeld = xcdatamodel_dir.extname != '.xcdatamodeld'
+          Gyro::Log.fail!('Please target an xcdatamodel inside your xcdatamodeld') unless is_xcdatamodeld
```
[the remark this answers is not in the document]
Comment (StevenWatremez) [reply lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: ok thanks for this

File: lib/gyro/parser/xcdatamodel/xcdatamodel.rb [hunk 4]
```diff
@@ -36,13 +36,19 @@ class XCDataModel
...
+          if xcdatamodel_dir.parent.extname == '.xcdatamodeld'
+            xcdatamodeld_info_message = 'You are using an xcdatamodeld, ' \
+                                        'please be sure you target the correct version of your xcdatamodel.' \
+                                        ' Actual version using by gyro is : ' + xcdatamodel_dir.basename.to_path
```
[the remark this answers is not in the document]
Comment (AliSoftware) [reply lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: And in english there's no space before `:`

File: lib/gyro/parser/xcdatamodel/xcdatamodel.rb [hunk 5]
```diff
@@ -36,13 +36,19 @@ class XCDataModel
...
+            Gyro::Log.info(xcdatamodeld_info_message)
+          end
+          file_contents = xcdatamodel_dir + 'contents'
+          Gyro::Log.fail!('Unable to find contents of xcdatamodel') unless file_contents.exist?
           @entities = {}
-          file = File.open(contents_file)
-          document_xml = Document.new(file)
-          file.close
-          load_entities(document_xml)
+          xml_document = Document.new(file_contents.open)
```
[the remark this answers is not in the document]
Comment (StevenWatremez) [reply lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: I did not find any information about REXML::Document with Pathname, the better solution is to rollback my changes.

File: lib/gyro/parser/xcdatamodel/xcdatamodel.rb [hunk 6]
```diff
@@ -37,18 +37,20 @@ class XCDataModel
...
             Gyro::Log.info(xcdatamodeld_info_message)
           end
           file_contents = xcdatamodel_dir + 'contents'
           Gyro::Log.fail!('Unable to find contents of xcdatamodel') unless file_contents.exist?
           @entities = {}
-          xml_document = Document.new(file_contents.open)
-          load_entities(xml_document)
+          file = File.open(file_contents)
+          document_xml = Document.new(file)
+          file.close
```
Comment (AliSoftware) [inline lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: `File.open` can take a trailing closure/block which will open the file, execute the block with the file handle, then auto-close the file.

```ruby
document_xml = File.open(file_contents) { |file| Document.new(file) }
```

That's more readable, and also safer as, in case there's an exception on the lines of code before open and close, the block syntax will catch the exception and close the file properly before rethrowing, instead of letting the file open.

File: lib/gyro/parser/xcdatamodel/xcdatamodel.rb [hunk 7]
```diff
@@ -37,18 +37,20 @@ class XCDataModel
 
         def initialize(xcdatamodel_dir)
           is_xcdatamodeld = xcdatamodel_dir.extname != '.xcdatamodeld'
-          Gyro::Log.fail!('Please target an xcdatamodel inside your xcdatamodeld') unless is_xcdatamodeld
+          Gyro::Log.fail!('Please target an \'.xcdatamodel\' file inside your xcdatamodeld') unless is_xcdatamodeld
```
Comment (AliSoftware) [inline lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: I'm surprised `rubocop` doesn't suggest you here to use `%q(Please target an '.xcdatamodel' file …)` syntax here (`%q(…)` allowing you to avoid having to escape the single quotes in the string)

File: spec/gyro/xcdatamodel_spec.rb [hunk 8]
```diff
@@ -27,7 +27,13 @@ module Gyro
     it 'check raise an error for xcdatamodeld' do
       xcdatamodel_dir = fixture('xcdatamodel', 'Model.xcdatamodeld')
       expect { Parser::XCDataModel::XCDataModel.new(xcdatamodel_dir) }
-        .to raise_error 'Please target an xcdatamodel inside your xcdatamodeld'
+        .to raise_error 'Please target an \'.xcdatamodel\' file inside your xcdatamodeld'
```
Comment (AliSoftware) [inline spec/gyro/xcdatamodel_spec.rb]: Same here (`%q`)

File: lib/gyro/parser/xcdatamodel/xcdatamodel.rb (hunk 7 above)
Comment (StevenWatremez) [reply lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: ok so I tried with `%q`but rubocop told that this syntax is only for string that contain both single quotes and double quotes. I seached and I found `%()` and `%Q()`.

Comment (StevenWatremez) [reply lib/gyro/parser/xcdatamodel/xcdatamodel.rb]: And rubocop tell me to use `%()` instead of `%Q()`
